name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "docs.azpays.net"

tls:
  enabled: false
  clusterIssuer: le-clusterissuer
  secretName: docs-azpays-net-wildcard-tls

image:
  repository: "azpays.{{ .Values.name }}-docs"
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}
